package com.sq.domain.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.sq.domain.bean.GreenFriend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_FRIEND".
*/
public class GreenFriendDao extends AbstractDao<GreenFriend, Long> {

    public static final String TABLENAME = "GREEN_FRIEND";

    /**
     * Properties of entity GreenFriend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property G_fid = new Property(0, Long.class, "g_fid", true, "_id");
        public final static Property Fid = new Property(1, String.class, "fid", false, "FID");
        public final static Property Uid = new Property(2, String.class, "uid", false, "UID");
    }

    private Query<GreenFriend> greenUser_FriendsQuery;

    public GreenFriendDao(DaoConfig config) {
        super(config);
    }
    
    public GreenFriendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_FRIEND\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: g_fid
                "\"FID\" TEXT UNIQUE ," + // 1: fid
                "\"UID\" TEXT);"); // 2: uid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_FRIEND\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenFriend entity) {
        stmt.clearBindings();
 
        Long g_fid = entity.getG_fid();
        if (g_fid != null) {
            stmt.bindLong(1, g_fid);
        }
 
        String fid = entity.getFid();
        if (fid != null) {
            stmt.bindString(2, fid);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenFriend entity) {
        stmt.clearBindings();
 
        Long g_fid = entity.getG_fid();
        if (g_fid != null) {
            stmt.bindLong(1, g_fid);
        }
 
        String fid = entity.getFid();
        if (fid != null) {
            stmt.bindString(2, fid);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GreenFriend readEntity(Cursor cursor, int offset) {
        GreenFriend entity = new GreenFriend( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // g_fid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // uid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenFriend entity, int offset) {
        entity.setG_fid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GreenFriend entity, long rowId) {
        entity.setG_fid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GreenFriend entity) {
        if(entity != null) {
            return entity.getG_fid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GreenFriend entity) {
        return entity.getG_fid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "friends" to-many relationship of GreenUser. */
    public List<GreenFriend> _queryGreenUser_Friends(Long g_fid) {
        synchronized (this) {
            if (greenUser_FriendsQuery == null) {
                QueryBuilder<GreenFriend> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.G_fid.eq(null));
                greenUser_FriendsQuery = queryBuilder.build();
            }
        }
        Query<GreenFriend> query = greenUser_FriendsQuery.forCurrentThread();
        query.setParameter(0, g_fid);
        return query.list();
    }

}
