package com.sq.domain.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sq.domain.bean.GreenUser;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_USER".
*/
public class GreenUserDao extends AbstractDao<GreenUser, Long> {

    public static final String TABLENAME = "GREEN_USER";

    /**
     * Properties of entity GreenUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property G_uid = new Property(0, Long.class, "g_uid", true, "_id");
        public final static Property Uid = new Property(1, String.class, "uid", false, "UID");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
    }

    private DaoSession daoSession;


    public GreenUserDao(DaoConfig config) {
        super(config);
    }
    
    public GreenUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: g_uid
                "\"UID\" TEXT UNIQUE ," + // 1: uid
                "\"USERNAME\" TEXT);"); // 2: username
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenUser entity) {
        stmt.clearBindings();
 
        Long g_uid = entity.getG_uid();
        if (g_uid != null) {
            stmt.bindLong(1, g_uid);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenUser entity) {
        stmt.clearBindings();
 
        Long g_uid = entity.getG_uid();
        if (g_uid != null) {
            stmt.bindLong(1, g_uid);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
    }

    @Override
    protected final void attachEntity(GreenUser entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GreenUser readEntity(Cursor cursor, int offset) {
        GreenUser entity = new GreenUser( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // g_uid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // username
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenUser entity, int offset) {
        entity.setG_uid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUsername(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GreenUser entity, long rowId) {
        entity.setG_uid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GreenUser entity) {
        if(entity != null) {
            return entity.getG_uid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GreenUser entity) {
        return entity.getG_uid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
